import React from 'react'
import BottomNav from '../../components/mobile/BottomNav'
import Header from '../../components/mobile/Header'
import DeskHeader from '../../components/desktop/DeskHeader'
import ResponsiveComponent from '../../components/ResponsiveComponent'
import Head from 'next/head'

const Custome404 = () => {
  return (
    <>
    <style jsx>{`
        .err-container {
            padding: 5px 8px;
        }
        .err-content {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100vh;
        }
    `}</style>
    <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div className='err-container'>
        <ResponsiveComponent Mobile={<Header />} Desktop={<DeskHeader />} />
        <div className='err-content'>
            <h1>404</h1>
        </div>
        <ResponsiveComponent Mobile={<BottomNav />} Desktop="" />
    </div>
    </>
  )
}

export default Custome404
